<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TUnit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/XetSharp/XetSharp.csproj" />
    <ProjectReference Include="../../src/XetSharp.Extensions.DependencyInjection/XetSharp.Extensions.DependencyInjection.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="ReferenceFiles/*" Exclude="ReferenceFiles/README.md" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="CapturedResponses/*" Exclude="CapturedResponses/README.md" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
